# Generated by Django 5.2.8 on 2025-11-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('sender', 'receiver', 'notification_type', 'post', 'comment')},
        ),
    ]
